'use client'
import { Inter, Saira } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/client/Navbar/Navbar'
import Footer from '@/components/client/Footer/Footer'
import { motion } from 'framer-motion';
import AuthProvider from '@/SessionProvider'
import { Provider } from 'react-redux'
import { PersistGate } from 'redux-persist/integration/react'

import {persistor, store} from "../redux/store"



const inter = Inter({ subsets: ['latin'] })
const saira = Saira({   weight: '400',
subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={saira.className}>
      <Provider store={store}>
      <PersistGate persistor={persistor}>
      <AuthProvider>
      <Navbar />
      <motion.div
      initial={{ opacity: 0, x: -50 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: 50 }}
      transition={{ duration: 0.5 }}
      >
        <div className='min-h-screen'>
        {children}
        </div>
        </motion.div>
        <Footer />

      </AuthProvider>
      </PersistGate>
      </Provider>
      </body>
    </html>
  )
}
