'use client'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/client/Nabar/Navbar'
import Footer from '@/components/client/Footer/Footer'
import { motion } from 'framer-motion';


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='transition-all ease-in'>
        <Navbar />
        <motion.div
          initial={{ opacity: 0, x: -50 }}
          animate={{ opacity: 1, x: 0 }}
          exit={{ opacity: 0, x: 50 }}
          transition={{ duration: 0.5 }}
         >

        {children}
        </motion.div>
        <Footer />

        </body>
    </html>
  )
}
